// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_emwind.Models;

namespace Mission06_emwind.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_emwind.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Drama",
                            Director = "Cameron Crowe",
                            Edited = false,
                            Rating = "PG",
                            Title = "We Bought a Zoo",
                            Year = 2011
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Romance",
                            Director = "George Tillman Jr",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Longest Ride",
                            Year = 2015
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Romance/Drama",
                            Director = "Joe Wright",
                            Edited = false,
                            Rating = "PG",
                            Title = "Pride and Prejudice",
                            Year = 2005
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
